import type { NextPage } from "next";
import React, { useEffect, useState } from "react";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import { MdKeyboardArrowRight } from "react-icons/md";
import Container from "../components/Container";
import Header from "../components/Header";
import Footer from "../components/Footer";
import Up from "../components/Up";
import Nav from "../components/Nav";
import PopularRestaurant from "../components/PopularRestaurant";
import Localities from "../components/Localities";
import {
  Category,
  CategoryItemGroup,
  CategoryItem,
  Collections,
  CollectionsTitle,
  CollectionsItemGroup,
  CollectionsItem,
  View,
  Cuisine,
  CuisineTitle,
  CuisineItem,
  CuisineItemGroup,
  MobileApp,
  ComputerFlex,
} from "../styles/HomePageStyle";

// 渲染資料
const CategoryData = [
  { pic: "/images/homePage/category/1.jpg", title: "Order Food Online" },
  { pic: "/images/homePage/category/2.jpg", title: "Go Out For Meal" },
  { pic: "/images/homePage/category/3.jpg", title: "Nightlife & Clubs" },
  { pic: "/images/homePage/category/4.jpg", title: "Pro Membership" },
];
const CollectionsData = [
  {
    pic: "/images/homePage/collections/1.png",
    title: "Most Searched of 2020",
    place: "30 Places",
  },
  {
    pic: "/images/homePage/collections/2.png",
    title: "Best Openings of 2020",
    place: "30 Places",
  },
  {
    pic: "/images/homePage/collections/3.png",
    title: "Trending This Week",
    place: "30 Places",
  },
  {
    pic: "/images/homePage/collections/4.png",
    title: "Best Of New York",
    place: "30 Places",
  },
];
const CuisineData = [
  {
    pic: "/images/homePage/cuisine/1.png",
    title: "Italian",
  },
  {
    pic: "/images/homePage/cuisine/2.png",
    title: "Chinesse",
  },
  {
    pic: "/images/homePage/cuisine/3.png",
    title: "Japanesse",
  },
  {
    pic: "/images/homePage/cuisine/4.png",
    title: "Indian",
  },
  {
    pic: "/images/homePage/cuisine/5.png",
    title: "Thai Food",
  },
  {
    pic: "/images/homePage/cuisine/6.png",
    title: "Mexican",
  },
];

const Home: NextPage = () => {
  // Fixed Nav 開關狀態
  const [isShow, setIsShow] = useState(false);
  // 監聽scroll 判斷開啟Nav
  const handleScroll = () => {
    // 滾動高度超過500 就開啟
    if (document.documentElement.scrollTop > 500) {
      setIsShow(true);
    } else {
      setIsShow(false);
    }
  };
  useEffect(() => {
    // 一掛載完就監聽
    window.addEventListener("scroll", handleScroll);
    // 卸載
    return () => {
      window.addEventListener("scroll", handleScroll);
    };
  }, []);
  return (
    <div>
      <Head>
        <title>foodHub</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Fixed Nav */}
      <Nav isShow={isShow} firstHeight={false} />
      {/* 頭部 */}
      <Header />
      {/* 返回頂部 */}
      <Up />

      {/* 分類區 */}
      <Category>
        <Container>
          <CategoryItemGroup>
            {CategoryData.map((v, i) => {
              return (
                <Link href="/FoodMenu" key={i}>
                  <a>
                    <CategoryItem>
                      <Image
                        src={v.pic}
                        alt=""
                        height="500px"
                        width="740px"
                        objectFit="cover"
                      />
                      <h3 className="title">{v.title}</h3>
                    </CategoryItem>
                  </a>
                </Link>
              );
            })}
          </CategoryItemGroup>
        </Container>
      </Category>
      {/* 收藏區 */}
      <Collections>
        <Container>
          <CollectionsTitle>Collections</CollectionsTitle>
          {/* 桌機 flex */}
          <ComputerFlex>
            <p>
              Explore curated lists of top restaurants, cafes, pubs, and bars in
              New York, based on trends
            </p>
            <View>View all collections</View>
          </ComputerFlex>
          <CollectionsItemGroup>
            {CollectionsData.map((v, i) => {
              return (
                <Link href="/SearchRestaurant" key={i}>
                  <a>
                    <CollectionsItem pic={v.pic}>
                      {/* 名稱 */}
                      <h3 className="title">{v.title}</h3>
                      {/* 場所 */}
                      <div className="place">
                        <span>{v.place}</span>
                        <MdKeyboardArrowRight />
                      </div>
                    </CollectionsItem>
                  </a>
                </Link>
              );
            })}
          </CollectionsItemGroup>
        </Container>
      </Collections>
      {/* 食物類型 */}
      <Cuisine>
        <Container>
          <CuisineTitle>Browse By Cuisine</CuisineTitle>
          <CuisineItemGroup>
            {CuisineData.map((v, i) => {
              return (
                <Link href="/FoodMenu" key={i}>
                  <a>
                    <CuisineItem>
                      <div className="pic">
                        <Image
                          src={v.pic}
                          alt=""
                          height="150px"
                          width="150px"
                        ></Image>
                      </div>
                      <h3 className="title">{v.title}</h3>
                    </CuisineItem>
                  </a>
                </Link>
              );
            })}
          </CuisineItemGroup>
        </Container>
      </Cuisine>
      {/* 人氣餐廳 */}
      <PopularRestaurant />
      {/* 手機App */}
      <MobileApp>
        <Container>
          <ComputerFlex>
            <div className="pic">
              <Image
                src="/images/homePage/App.4927ff9.png"
                alt=""
                height={370}
                width={185}
              />
            </div>
            <div className="content">
              <div className="title">Get the Mobile App</div>
              <h4>
                We will send you a link, open it on your phone to download the
                app
              </h4>
              <div className="radios">
                {/* 單選 name 要一樣 */}
                <input type="radio" name="option" id="email" />
                <label htmlFor="email">Email</label>
                <input type="radio" name="option" id="phone" />
                <label htmlFor="phone">Phone</label>
              </div>
              <div className="search">
                <input type="text" placeholder="Email" />
                <button>SEARCH</button>
              </div>
              <div className="download">
                <p>Download App from</p>
                <div className="load-point">
                  <div className="google-play">
                    <Image
                      src="/images/google-play.png"
                      alt=""
                      height={50}
                      width={150}
                    />
                  </div>
                  <div className="app-store">
                    <Image
                      src="/images/app-store.png"
                      alt=""
                      height={50}
                      width={150}
                    />
                  </div>
                </div>
              </div>
            </div>
          </ComputerFlex>
        </Container>
      </MobileApp>
      <Localities />
      <Footer />
    </div>
  );
};

export default Home;
